ARG NODE_TAG
ARG NGINX_TAG
FROM node:${NODE_TAG} AS build

ARG BUILD_ENV

WORKDIR /home/node

COPY package*.json ./

RUN npm install

COPY . .

RUN $(npm bin)/ng build $BUILD_ENV --output-path=dist

FROM nginx:${NGINX_TAG}
COPY ./configs/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /home/node/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
